import * as Blockly from "blockly/core"

export const blocks = Blockly.common.createBlockDefinitionsFromJsonArray([
  {
    type: "accent_color",
    message0: "accent-color: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "all",
    message0: "all: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "anchor_name",
    message0: "anchor-name: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "anchor_scope",
    message0: "anchor-scope: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "animation",
    message0: "animation: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "animation_composition",
    message0: "animation-composition: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "appearance",
    message0: "appearance: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "aspect_ratio",
    message0: "aspect-ratio: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "backdrop_filter",
    message0: "backdrop-filter: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "backface_visibility",
    message0: "backface-visibility: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "background",
    message0: "background: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "background_blend_mode",
    message0: "background-blend-mode: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "border",
    message0: "border: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "border_collapse",
    message0: "border-collapse: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "border_image",
    message0: "border-image: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "border_radius",
    message0: "border-radius: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "border_spacing",
    message0: "border-spacing: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "box_shadow",
    message0: "box-shadow: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "box_sizing",
    message0: "box-sizing: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "break_after",
    message0: "break-after: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "break_before",
    message0: "break-before: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "break_inside",
    message0: "break-inside: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "caption_side",
    message0: "caption-side: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "caret_color",
    message0: "caret-color: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "clear",
    message0: "clear: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "clip_path",
    message0: "clip-path: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "color",
    message0: "color: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "color_scheme",
    message0: "color-scheme: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "column_fill",
    message0: "column-fill: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "column_rule",
    message0: "column-rule: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "column_span",
    message0: "column-span: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "columns",
    message0: "columns: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "contain",
    message0: "contain: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "contain_intrinsic_size",
    message0: "contain-intrinsic-size: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "container",
    message0: "container: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "content",
    message0: "content: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "content_visibility",
    message0: "content-visibility: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "counter_increment",
    message0: "counter-increment: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "counter_reset",
    message0: "counter-reset: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "counter_set",
    message0: "counter-set: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "cursor",
    message0: "cursor: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "direction",
    message0: "direction: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "display",
    message0: "display: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "empty_cells",
    message0: "empty-cells: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "field_sizing",
    message0: "field-sizing: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "filter",
    message0: "filter: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "flex",
    message0: "flex: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "flex_flow",
    message0: "flex-flow: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "float",
    message0: "float: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "font",
    message0: "font: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "font_feature_settings",
    message0: "font-feature-settings: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "font_kerning",
    message0: "font-kerning: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "font_optical_sizing",
    message0: "font-optical-sizing: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "font_palette",
    message0: "font-palette: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "font_size_adjust",
    message0: "font-size-adjust: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "font_synthesis",
    message0: "font-synthesis: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "font_variation_settings",
    message0: "font-variation-settings: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "gap",
    message0: "gap: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "grid",
    message0: "grid: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "grid_area",
    message0: "grid-area: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "height",
    message0: "height: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "hyphenate_character",
    message0: "hyphenate-character: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "hyphens",
    message0: "hyphens: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "image_orientation",
    message0: "image-orientation: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "image_rendering",
    message0: "image-rendering: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "inset",
    message0: "inset: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "isolation",
    message0: "isolation: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "letter_spacing",
    message0: "letter-spacing: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "line_break",
    message0: "line-break: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "list_style",
    message0: "list-style: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "margin",
    message0: "margin: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "mask",
    message0: "mask: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "max_height",
    message0: "max-height: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "max_width",
    message0: "max-width: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "min_height",
    message0: "min-height: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "min_width",
    message0: "min-width: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "mix_blend_mode",
    message0: "mix-blend-mode: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "object_fit",
    message0: "object-fit: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "object_position",
    message0: "object-position: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "offset",
    message0: "offset: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "opacity",
    message0: "opacity: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "order",
    message0: "order: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "outline",
    message0: "outline: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "outline_offset",
    message0: "outline-offset: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "overflow",
    message0: "overflow: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "overflow_anchor",
    message0: "overflow-anchor: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "overflow_wrap",
    message0: "overflow-wrap: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "overscroll_behavior",
    message0: "overscroll-behavior: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "padding",
    message0: "padding: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "page",
    message0: "page: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "paint_order",
    message0: "paint-order: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "perspective",
    message0: "perspective: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "perspective_origin",
    message0: "perspective-origin: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "place_content",
    message0: "place-content: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "place_items",
    message0: "place-items: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "place_self",
    message0: "place-self: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "pointer_events",
    message0: "pointer-events: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "position",
    message0: "position: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "position_anchor",
    message0: "position-anchor: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "position_area",
    message0: "position-area: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "position_try",
    message0: "position-try: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "position_visibility",
    message0: "position-visibility: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "print_color_adjust",
    message0: "print-color-adjust: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "quotes",
    message0: "quotes: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "resize",
    message0: "resize: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "rotate",
    message0: "rotate: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "ruby_align",
    message0: "ruby-align: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "ruby_position",
    message0: "ruby-position: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "scale",
    message0: "scale: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "scroll_behavior",
    message0: "scroll-behavior: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "scroll_margin",
    message0: "scroll-margin: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "scroll_padding",
    message0: "scroll-padding: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "scroll_snap_align",
    message0: "scroll-snap-align: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "scroll_snap_stop",
    message0: "scroll-snap-stop: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "scroll_snap_type",
    message0: "scroll-snap-type: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "scrollbar_color",
    message0: "scrollbar-color: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "scrollbar_gutter",
    message0: "scrollbar-gutter: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "scrollbar_width",
    message0: "scrollbar-width: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "shape_image_threshold",
    message0: "shape-image-threshold: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "shape_margin",
    message0: "shape-margin: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "shape_outside",
    message0: "shape-outside: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "tab_size",
    message0: "tab-size: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "table_layout",
    message0: "table-layout: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "text_align",
    message0: "text-align: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "text_align_last",
    message0: "text-align-last: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "text_autospace",
    message0: "text-autospace: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "text_box",
    message0: "text-box: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "text_combine_upright",
    message0: "text-combine-upright: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "text_decoration",
    message0: "text-decoration: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "text_decoration_skip_ink",
    message0: "text-decoration-skip-ink: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "text_emphasis",
    message0: "text-emphasis: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "text_emphasis_position",
    message0: "text-emphasis-position: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "text_indent",
    message0: "text-indent: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "text_orientation",
    message0: "text-orientation: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "text_overflow",
    message0: "text-overflow: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "text_rendering",
    message0: "text-rendering: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "text_shadow",
    message0: "text-shadow: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "text_transform",
    message0: "text-transform: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "text_underline_offset",
    message0: "text-underline-offset: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "text_underline_position",
    message0: "text-underline-position: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "text_wrap",
    message0: "text-wrap: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "touch_action",
    message0: "touch-action: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "transform",
    message0: "transform: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "transform_box",
    message0: "transform-box: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "transform_origin",
    message0: "transform-origin: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "transform_style",
    message0: "transform-style: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "transition",
    message0: "transition: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "translate",
    message0: "translate: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "unicode_bidi",
    message0: "unicode-bidi: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "vertical_align",
    message0: "vertical-align: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "view_transition_class",
    message0: "view-transition-class: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "view_transition_name",
    message0: "view-transition-name: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "visibility",
    message0: "visibility: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "white_space",
    message0: "white-space: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "width",
    message0: "width: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "will_change",
    message0: "will-change: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "word_break",
    message0: "word-break: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "word_spacing",
    message0: "word-spacing: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "writing_mode",
    message0: "writing-mode: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "z_index",
    message0: "z-index: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
  {
    type: "zoom",
    message0: "zoom: %1;",
    args0: [{ type: "field_input", name: "VALUE", text: "" }],
    previousStatement: null,
    nextStatement: null,
    style: "",
    tooltip: "",
  },
] satisfies Blockly.JsonBlockDefinition[])
